### ISSUE TITLE
How to add border?

### ISSUE THREAD

**Issue by JasonHezz** [ceryle/SegmentedButton#2]
I tried to add background to SegmentedButtonGroup, however it wasn't work.
Background code:
```
<?xml version="1.0" encoding="utf-8"?>
<shape xmlns:android="http://schemas.android.com/apk/res/android">
  <corners android:radius="5dp"/>
  <stroke
      android:color="@color/colorPrimary"
      android:width="1dp"
      />
</shape>
```
Want to behave like this library [android-segmented-control](https://github.com/Kaopiz/android-segmented-control).

**Comment by ceryle** [comment]
Hi,
I released a new version of the library. Now, you can add border with these attributes:

```
<co.ceryle.segmentedbutton.SegmentedButtonGroup
     ...
     app:sbg_borderSize="1dp"
     app:sbg_borderColor="@color/black" />
```

**Comment by JasonHezz** [comment]
Unfortunatly it still cannot work.
![image](https://cloud.githubusercontent.com/assets/15358765/19381429/16164220-922e-11e6-8667-5252900587d2.png)
Here is my SegmentedButtonGroup code 
```
<co.ceryle.segmentedbutton.SegmentedButtonGroup
        android:id="@+id/segmentedButtonGroup"
        android:layout_width="185dp"
        android:layout_height="wrap_content"
        android:layout_centerHorizontal="true"
        android:layout_margin="10dp"
        android:visibility="gone"
        app:sbg_animateSelector="accelerate"
        app:sbg_animateSelectorDuration="200"
        app:sbg_backgroundColor="@color/white"
        app:sbg_borderColor="@color/yancy_teal600"
        app:sbg_borderSize="1dp"
        app:sbg_dividerSize="0dp"
        app:sbg_position="0"
        app:sbg_radius="5dp"
        app:sbg_ripple="true"
        app:sbg_rippleColor="@color/yancy_teal600"
        app:sbg_selectorColor="@color/yancy_teal600"
        app:sbg_selectorTextColor="@color/white"
        app:sbg_shadow="false"
        >
        ....
</SegmentedButtonGroup>
```

**Comment by ceryle** [comment]
I released v1.1.1 and I believe it works now.

**Comment by JasonHezz** [comment]
Ok!Thank you for replying so quickly

**Comment by ceryle** [comment]
You're welcome. I’m happy to help.
